### ISSUE TITLE
New HA Energy Dashboard

### ISSUE THREAD

**Issue by mobiledude2** [heinoldenhuis/home_assistant_omnik_solar#14]
Hi, Is there a way that this integration is adjusted to support the new Energy Dashboard in current beta version of Home Assistant? https://rc.home-assistant.io/blog/2021/07/28/release-20218/

**Comment by tharealmb** [comment]
New URL for the info: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by Veenrijk** [comment]
It would be nice if there was a permanent solution

**Comment by turnmike2** [comment]
Also for me. As the Energy dashboard evolves, a structural solution would be nice.
I added the mentioned setting and worked quite well for 2021.08.
With the new options having long term data, I notice negative values in the week/month/year reports.

If someone have other options, please share.

**Comment by hultenvp** [comment]
I created a pull request with a structural fix to support the energy dashboard.

To support Energy Dashboard entities must be derived from base class SensorEntity.
Hopefully @heinoldenhuis is able to integrate this and create a new release.

If you cannot wait then you could consider using my fork via "custom integrations" in HACS:
https://github.com/hultenvp/home_assistant_omnik_solar

**Comment by freekvh** [comment]
> I created a pull request with a structural fix to support the energy dashboard.
> 
> To support Energy Dashboard entities must be derived from base class SensorEntity. Hopefully @heinoldenhuis is able to integrate this and create a new release.
> 
> If you cannot wait then you could consider using my fork via "custom integrations" in HACS: https://github.com/hultenvp/home_assistant_omnik_solar

Hi @hultenvp I tried your fork, I have all the sensors outputting "unknown" (onbekend), except for MyOmnik Actual Power which reads 0 W. Am I missing something? (the same happens for this original repo). I'm on 2021.11.4 (running the Docker).

**Comment by freekvh** [comment]
> > I created a pull request with a structural fix to support the energy dashboard.
> > To support Energy Dashboard entities must be derived from base class SensorEntity. Hopefully @heinoldenhuis is able to integrate this and create a new release.
> > If you cannot wait then you could consider using my fork via "custom integrations" in HACS: https://github.com/hultenvp/home_assistant_omnik_solar
> 
> Hi @hultenvp I tried your fork, I have all the sensors outputting "unknown" (onbekend), except for MyOmnik Actual Power which reads 0 W. Am I missing something? (the same happens for this original repo). I'm on 2021.11.4 (running the Docker).

Never mind, I was given the wrong IP address, it works now! Absolutely great, thank you!!

**Comment by hultenvp** [comment]
I was just writing instructions how to debug ;-). Good that it works now. Enjoy.

**Comment by freekvh** [comment]
> I was just writing instructions how to debug ;-). Good that it works now. Enjoy.

One issues I've been running into btw, sometimes the Omnik stops talking to Home Assistant, even though the Omnik app keeps receiving data. This is fixed by restarting Home Assistant. Does this sound familiar? My father does have pretty poor wifi so it could perhaps be that the connection drops, and then never restores (even though it could)?

**Comment by hultenvp** [comment]
Not sure, don't recognize it from my own usage. Runs pretty stable for me. Did it run more stable before switching to my PR?

I'm still relatively new to python myself, but the code also gives me no leads to what could be wrong. Had some issues in the past with my own integration that I did not properly clean up connections in all cases. This integration opens a new TCP socket connection every time it wants to read and also closes the connection nicely after reading, also if something goes wrong, so I don't think that's the issue here.

The only thing I can imagine is that home assistant has specific behaviour is the integration goes offline (status switches to offline if it fails to read from the inverter). Perhaps it gives up polling after a while if the connection is considered down due to connection being too flakey. You could check in the discord channels if someone knows if this could be the case.

**Comment by freekvh** [comment]
> Not sure, don't recognize it from my own usage. Runs pretty stable for me. Did it run more stable before switching to my PR?
> 
> I'm still relatively new to python myself, but the code also gives me no leads to what could be wrong. Had some issues in the past with my own integration that I did not properly clean up connections in all cases. This integration opens a new TCP socket connection every time it wants to read and also closes the connection nicely after reading, also if something goes wrong, so I don't think that's the issue here.
> 
> The only thing I can imagine is that home assistant has specific behaviour is the integration goes offline (status switches to offline if it fails to read from the inverter). Perhaps it gives up polling after a while if the connection is considered down due to connection being too flakey. You could check in the discord channels if someone knows if this could be the case.

Thanx for your response. You PR has been running for some days without issue now. It could just be my father's poor wifi. I'll keep an eye on it, maybe I can produce some logs next time it happens.

**Comment by pvmil** [comment]
Will this be merged into a new release for HACS? Would really like to have this feature

**Comment by heinoldenhuis** [comment]
Hi all, currently I am not using the component. Was quit busy last weeks, but will check the PR in the next days and will create a new release. Looks good by the way.

**Comment by hultenvp** [comment]
@heinoldenhuis : I'm happy to help in the development/maintenance of this integration if you want. Just let me know.

**Comment by heinoldenhuis** [comment]
@hultenvp I do not have the time for developing and maintaining. Currently I am not using this component myself.
I will remove this component from HACS and archive it. You or someone are welcome to use this code and create a own component for further use on a different repository.
